// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9V-kvMvb3zuC_p0nbE1aN62ngQGqgXOk',
    appId: '1:557292797823:web:5fca315655580e9028e44a',
    messagingSenderId: '557292797823',
    projectId: 'chatapp-10e5b',
    authDomain: 'chatapp-10e5b.firebaseapp.com',
    storageBucket: 'chatapp-10e5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZTf7AUaIgid5spe2L0pe0TV4Ii3mxl-8',
    appId: '1:557292797823:android:588773f22965751028e44a',
    messagingSenderId: '557292797823',
    projectId: 'chatapp-10e5b',
    storageBucket: 'chatapp-10e5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCALhWDrDUECjeURj5sKg6fbJvr7aJBpqc',
    appId: '1:557292797823:ios:9015a19fbb31935b28e44a',
    messagingSenderId: '557292797823',
    projectId: 'chatapp-10e5b',
    storageBucket: 'chatapp-10e5b.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCALhWDrDUECjeURj5sKg6fbJvr7aJBpqc',
    appId: '1:557292797823:ios:4589260ccd114f0728e44a',
    messagingSenderId: '557292797823',
    projectId: 'chatapp-10e5b',
    storageBucket: 'chatapp-10e5b.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
